# This is a basic workflow that is manually triggered

name: GitHub Action for Firebase

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main

  pull_request:
    branches:
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  firebase-deploy:
    name: Deploy Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.0
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install Functions Dependencies
        run: |
          cd firebase/functions
          pnpm install --frozen-lockfile

      - name: Deploy hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --message \"${{ github.event.head_commit.message }}\"
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy functions
        uses: w9jds/firebase-action@master
        with:
          args: |
            npm install -g pnpm@10.11.0 && 
            deploy --only functions --message "${{ github.event.head_commit.message }}"
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
