# This is a basic workflow that is manually triggered

name: GitHub Action for Firebase

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
    - main
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-hosting:
    name: Deploy Firebase
    environment: 
      name: firebase-deploy
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Install Functions Dependencies
        run: cd functions && npm install
      - name: Install firebase-tools
        run: npm install -g firebase-tools
      - name: Setup Firebase
        run: firebase use --add $PROJECT_ID
      - name: Deploy hosting
        run: firebase deploy --only hosting --token $FIREBASE_TOKEN --message \"${{ github.event.head_commit.message }}\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy functions
        run: firebase deploy --only functions --token $FIREBASE_TOKEN --message \"${{ github.event.head_commit.message }}\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}